mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  typeAliasesPackage: classpath*:com.jerry.**.domain

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learning
    username: root
    password: 123456